import assert from "node:assert/strict";
import test from "node:test";
import { ApiError, type GoogleGenAI } from "@google/genai";
import { z } from "zod";
import { AiError } from "../../errors/ai-error.js";
import { GeminiProvider } from "./gemini-provider.js";
const signal = new AbortController().signal;
const request = { task: "text" as const, modelRole: "FAST" as const, provider: "GEMINI" as const, model: "configured-gemini", system: "Be concise", messages: [{ role: "user" as const, content: "hello" }, { role: "assistant" as const, content: "hi" }], maxOutputTokens: 20, signal };
function client(response: object | Error, capture?: (input: object) => void) { return { models: { generateContent: async (input: object) => { capture?.(input); if (response instanceof Error) throw response; return response; } } } as unknown as GoogleGenAI; }
test("Gemini adapter normalizes requests, responses, and usage", async () => { let sent: object | undefined; const provider = new GeminiProvider("secret", client({ text: "ready", modelVersion: "configured-gemini", responseId: "gemini-1", candidates: [{ finishReason: "STOP" }], usageMetadata: { promptTokenCount: 10, cachedContentTokenCount: 4, candidatesTokenCount: 3, totalTokenCount: 13 } }, (value) => { sent = value; })); const result = await provider.generateText(request); assert.deepEqual(result.usage, { inputTokens: 10, cachedInputTokens: 4, outputTokens: 3, totalTokens: 13 }); assert.equal(result.provider, "GEMINI"); assert.equal(result.requestId, "gemini-1"); assert.deepEqual((sent as { contents: unknown }).contents, [{ role: "user", parts: [{ text: "hello" }] }, { role: "model", parts: [{ text: "hi" }] }]); assert.equal("usageMetadata" in result, false); });
test("Gemini structured output is independently validated", async () => { const schema = z.object({ ready: z.boolean() }); const valid = new GeminiProvider("secret", client({ text: JSON.stringify({ ready: true }) })); assert.deepEqual((await valid.generateStructured({ ...request, task: "structured", schemaName: "ready", schema })).output, { ready: true }); const invalid = new GeminiProvider("secret", client({ text: JSON.stringify({ ready: "yes" }) })); await assert.rejects(() => invalid.generateStructured({ ...request, task: "structured", schemaName: "ready", schema }), (error) => error instanceof AiError && error.code === "INVALID_PROVIDER_RESPONSE"); });
test("Gemini errors are safely classified", async () => { const transient = new GeminiProvider("secret", client(new ApiError({ status: 503, message: "secret upstream" }))); await assert.rejects(() => transient.generateText(request), (error) => error instanceof AiError && error.retryable && !error.message.includes("secret upstream")); const rejected = new GeminiProvider("secret", client(new ApiError({ status: 400, message: "secret prompt" }))); await assert.rejects(() => rejected.generateText(request), (error) => error instanceof AiError && error.code === "PROVIDER_REJECTED" && !error.message.includes("secret prompt")); });
test("Gemini cancellation is normalized", async () => { const aborted = new Error("cancelled"); aborted.name = "AbortError"; await assert.rejects(() => new GeminiProvider("secret", client(aborted)).generateText(request), (error) => error instanceof AiError && error.code === "CANCELLED"); });
