"use client";
import { Braces, Database, Eye, FileCode2, Hammer, Rocket, Settings, TerminalSquare } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ApiClientError } from "@/lib/api/client";
import { projectApi } from "@/lib/api/control-plane-service";
import type { Project, ProjectEnvironment } from "@/lib/api/types";
import { useOrganization } from "../organizations/organization-provider";
import { AiComposer } from "./ai-composer";
const tabs = ["Preview", "Files", "Database", "Logs", "Build", "Settings"] as const; type Tab = typeof tabs[number];
const content: Record<Exclude<Tab, "Settings">, [React.ElementType, string, string]> = {
  Preview: [Eye, "Preview unavailable", "A live runtime preview will appear here after project generation and isolated builds are implemented."], Files: [FileCode2, "No generated files", "Generated project files will appear here. No source files have been fabricated."], Database: [Database, "Project database not provisioned", "This panel will manage databases belonging to generated customer projects—not Zayloq's control-plane database."], Logs: [TerminalSquare, "No runtime logs", "Build and preview logs will appear once an isolated runtime exists."], Build: [Hammer, "Build pipeline not connected", "Planning, generation, installation, validation, repair, and preview stages will be reported here."]
};
export function WorkspaceShell({ projectId }: { projectId: string }) {
  const router = useRouter(); const organizations = useOrganization(); const [project, setProject] = useState<Project>(); const [environments, setEnvironments] = useState<ProjectEnvironment[]>([]); const [tab, setTab] = useState<Tab>("Preview"); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; Promise.all([projectApi.get(projectId), projectApi.environments(projectId)]).then(([projectResult, environmentResult]) => { if (active) { setProject(projectResult.project); setEnvironments(environmentResult.environments); } }).catch((cause) => { if (!active) return; if (cause instanceof ApiClientError && cause.status === 401) router.replace(`/login?next=${encodeURIComponent(`/projects/${projectId}`)}`); else setError(cause instanceof ApiClientError ? cause.message : "The project could not be loaded."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [projectId, router]);
  if (loading) return <div className="data-state" role="status">Loading project…</div>; if (error || !project) return <div className="data-state error" role="alert">{error || "Project not found."}</div>;
  const organization = organizations.organizations.find((item) => item.id === project.organizationId);
  return <section className="workspace"><header className="workspace-header"><div><span className="eyebrow">{organization?.name ?? "Project workspace"}</span><h1>{project.name}</h1><p>{project.status} · {environments.map((item) => item.type).join(", ") || "No environments"}</p></div><div><button className="secondary-button" disabled><Eye /> Preview</button><button className="primary-button small" disabled><Rocket /> Deploy</button></div></header><div className="workspace-grid"><aside className="ai-panel"><div className="panel-label"><Braces /> Zayloq AI</div><div className="conversation-empty"><div className="spark-icon"><Braces /></div><h2>Planning not connected</h2><p>This real project is ready to become the ownership boundary for future planning and generation.</p></div><AiComposer compact /></aside><div className="runtime-panel"><div role="tablist" aria-label="Project workspace panels" className="workspace-tabs">{tabs.map((item) => <button key={item} role="tab" aria-selected={tab === item} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Settings" ? <ProjectSettings project={project} onProject={setProject} /> : <WorkspacePanel tab={tab} />}</div></div></section>;
}
function WorkspacePanel({ tab }: { tab: Exclude<Tab, "Settings"> }) { const [Icon, title, description] = content[tab]; return <div className="workspace-empty"><div><Icon /><span>Future capability</span></div><h2>{title}</h2><p>{description}</p></div>; }
function ProjectSettings({ project, onProject }: { project: Project; onProject(project: Project): void }) {
  const router = useRouter(); const [name, setName] = useState(project.name); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function rename(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { onProject((await projectApi.update(project.id, name)).project); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "The project could not be updated."); } finally { setBusy(false); } }
  async function archive() { if (!window.confirm(`Archive ${project.name}? It will leave the active project list.`)) return; setBusy(true); setError(""); try { await projectApi.archive(project.id); router.push("/projects"); router.refresh(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "The project could not be archived."); setBusy(false); } }
  return <div className="project-settings"><Settings /><h2>Project settings</h2><form onSubmit={rename}><label htmlFor="rename-project">Project name</label><input id="rename-project" value={name} onChange={(event) => setName(event.target.value)} maxLength={160} required /><button className="primary-button small" disabled={busy || name.trim() === project.name}>Save name</button></form>{error && <p role="alert" className="form-error">{error}</p>}<div className="danger-zone"><div><strong>Archive project</strong><p>Archiving preserves project history but removes it from active lists.</p></div><button className="secondary-button" disabled={busy} onClick={() => void archive()}>Archive project</button></div></div>;
}
