"use client";
import Link from "next/link";
import { Box, FolderKanban, Plus, Rocket, Sparkles } from "lucide-react";
import { useCallback, useState } from "react";
import type { PublicUser } from "@/lib/api/types";
import { useOrganization } from "../organizations/organization-provider";
import { ProjectList } from "../projects/project-list";
export function Dashboard({ user }: { user: PublicUser }) {
  const name = user.displayName?.split(" ")[0] ?? "builder"; const organization = useOrganization(); const [count, setCount] = useState(0); const onCount = useCallback((value: number) => setCount(value), []);
  return <div className="page-stack"><header className="page-heading"><div><span className="eyebrow">Control center</span><h1>Welcome back, {name}.</h1><p>{organization.current ? `${organization.current.name} · ${organization.current.role}` : "Your organization will be created with your first project."}</p></div><Link href="/projects/new" className="primary-button small"><Plus /> Create project</Link></header><section className="metric-grid"><Metric icon={FolderKanban} label="Projects" value={String(count)} note="Active persisted projects" /><Metric icon={Box} label="Recent builds" value="—" note="Build runtime not connected" /><Metric icon={Rocket} label="Deployments" value="—" note="Deployment arrives later" /><Metric icon={Sparkles} label="Usage" value="—" note="Usage tracking arrives later" /></section><section className="dashboard-grid"><div className="surface-card wide"><div className="section-title"><div><span className="eyebrow">Projects</span><h2>Recent projects</h2></div></div><ProjectList compact onCount={onCount} /></div><div className="surface-card"><span className="eyebrow">Account</span><h2>Ready to build</h2><div className="identity-card"><div className="avatar large">{(user.displayName ?? user.email)[0]?.toUpperCase()}</div><div><strong>{user.displayName ?? "Zayloq user"}</strong><span>{user.email}</span></div></div><div className={`verification-status ${user.emailVerified ? "verified" : ""}`}><span />{user.emailVerified ? "Email verified" : "Email verification pending"}</div></div></section></div>;
}
function Metric({ icon: Icon, label, value, note }: { icon: React.ElementType; label: string; value: string; note: string }) { return <article className="metric-card"><div><Icon /><span>{label}</span></div><strong>{value}</strong><p>{note}</p></article>; }
