import OpenAI from "openai";
import { z } from "zod";
import type { AiProvider, AiResponse, AiUsage, ResolvedAiRequest, ResolvedStructuredRequest } from "../../contracts/types.js";
import { AiError } from "../../errors/ai-error.js";

type ResponsesClient = Pick<OpenAI["responses"], "create">;
function usage(value: { input_tokens?: number; output_tokens?: number; total_tokens?: number } | undefined): AiUsage { return { ...(value?.input_tokens !== undefined ? { inputTokens: value.input_tokens } : {}), ...(value?.output_tokens !== undefined ? { outputTokens: value.output_tokens } : {}), ...(value?.total_tokens !== undefined ? { totalTokens: value.total_tokens } : {}) }; }
function input(request: ResolvedAiRequest) { return request.messages.map((message) => ({ role: message.role, content: message.content })); }
function providerError(error: unknown): never { if (error instanceof AiError) throw error; if (error instanceof OpenAI.APIError) { if (error.status === 429) throw new AiError("RATE_LIMITED", "The AI provider is temporarily rate limited.", true); if (error.status && error.status >= 500) throw new AiError("PROVIDER_UNAVAILABLE", "The AI provider is temporarily unavailable.", true); if (error.status === 401 || error.status === 403) throw new AiError("CONFIGURATION_ERROR", "The AI provider configuration is invalid."); throw new AiError("PROVIDER_REJECTED", "The AI provider rejected the request."); } if (error instanceof Error && error.name === "AbortError") throw new AiError("CANCELLED", "The AI request was cancelled."); throw new AiError("PROVIDER_UNAVAILABLE", "The AI provider is temporarily unavailable.", true); }
export class OpenAiProvider implements AiProvider {
  readonly name = "OPENAI" as const; private readonly responses: ResponsesClient;
  constructor(apiKey: string, client?: OpenAI) { this.responses = (client ?? new OpenAI({ apiKey, maxRetries: 0 })).responses; }
  async generateText(request: ResolvedAiRequest): Promise<AiResponse<string>> { const started = Date.now(); try { const response = await this.responses.create({ model: request.model, instructions: request.system, input: input(request), max_output_tokens: request.maxOutputTokens, temperature: request.temperature, store: false }, { signal: request.signal }); const output = response.output_text?.trim(); if (!output) throw new AiError("INVALID_PROVIDER_RESPONSE", "The AI provider returned an invalid response."); return { provider: this.name, model: response.model, output, finishReason: response.status ?? null, usage: usage(response.usage), latencyMs: Date.now() - started, requestId: response.id, retryCount: 0 }; } catch (error) { return providerError(error); } }
  async generateStructured<T>(request: ResolvedStructuredRequest<T>): Promise<AiResponse<T>> { const started = Date.now(); try { const response = await this.responses.create({ model: request.model, instructions: request.system, input: input(request), max_output_tokens: request.maxOutputTokens, temperature: request.temperature, store: false, text: { format: { type: "json_schema", name: request.schemaName, strict: true, schema: z.toJSONSchema(request.schema) } } }, { signal: request.signal }); let decoded: unknown; try { decoded = JSON.parse(response.output_text); } catch { throw new AiError("INVALID_PROVIDER_RESPONSE", "The AI provider returned invalid structured output."); } const parsed = request.schema.safeParse(decoded); if (!parsed.success) throw new AiError("INVALID_PROVIDER_RESPONSE", "The AI provider returned invalid structured output."); return { provider: this.name, model: response.model, output: parsed.data, finishReason: response.status ?? null, usage: usage(response.usage), latencyMs: Date.now() - started, requestId: response.id, retryCount: 0 }; } catch (error) { return providerError(error); } }
}
