import { getAiConfigurationState, loadAiBillingEnvironment, loadAiEnvironment } from "@zayloq/config";
import { createAiGateway } from "../gateway/factory.js";
import { CatalogAiCostCalculator, pricingCatalogFromJson } from "../usage/cost-accounting.js";
import { CostPlusCreditPolicy } from "../usage/credit-pricing.js";
import { MeteredAiGateway } from "../usage/metered-ai-gateway.js";
import { UsageAccountingService } from "../usage/usage-accounting.js";
if (process.env.ZAYLOQ_RUN_REAL_GEMINI_SMOKE !== "true") { console.log("Gemini billing smoke: SKIPPED (set ZAYLOQ_RUN_REAL_GEMINI_SMOKE=true to opt in)."); process.exit(0); }
const state = getAiConfigurationState({ ...process.env, AI_DEFAULT_PROVIDER: "GEMINI" }); if (state.providers.GEMINI !== "configured") { console.log("Gemini billing smoke: SKIPPED (Gemini configuration unavailable)."); process.exit(0); }
let billing; try { billing = loadAiBillingEnvironment(); } catch { console.log("Gemini billing smoke: SKIPPED (pricing configuration unavailable)."); process.exit(0); }
const config = loadAiEnvironment({ ...process.env, AI_DEFAULT_PROVIDER: "GEMINI" }); const { getDatabaseClient } = await import("@zayloq/database"); const db = getDatabaseClient(); const accounting = new UsageAccountingService(db); const key = crypto.randomUUID(); const user = await db.user.create({ data: { email: `gemini-smoke-${key}@example.test` } }); const organization = await db.organization.create({ data: { name: "Gemini smoke fixture", slug: `gemini-smoke-${key}` } }); await db.membership.create({ data: { userId: user.id, organizationId: organization.id, role: "OWNER" } }); await accounting.grantForTesting(organization.id, BigInt(10_000_000), key);
try {
  const metered = new MeteredAiGateway(await createAiGateway(config), accounting, new CatalogAiCostCalculator(pricingCatalogFromJson(billing.AI_PRICING_CATALOG_JSON)), new CostPlusCreditPolicy({ unitsPerCurrencyMicro: BigInt(billing.AI_CREDIT_UNITS_PER_CURRENCY_MICRO), markupBasisPoints: BigInt(billing.AI_CREDIT_MARKUP_BPS), minimumChargeUnits: BigInt(billing.AI_CREDIT_MIN_CHARGE_UNITS), version: "configured-v1" }));
  const result = await metered.generateText({ task: "text", modelRole: "FAST", provider: "GEMINI", system: "Follow the user's exact output instruction.", messages: [{ role: "user", content: "Return exactly the word ZAYLOQ_READY." }], maxOutputTokens: 16 }, { organizationId: organization.id, userId: user.id, operationType: "GEMINI_SMOKE", idempotencyKey: key, reservationUnits: BigInt(10_000_000), provider: "GEMINI", model: config.ZAYLOQ_AI_GEMINI_FAST_MODEL! });
  if (result.output.trim() !== "ZAYLOQ_READY") throw new Error("Gemini smoke response did not match the expected value."); const event = await db.aiUsageEvent.findFirstOrThrow({ where: { organizationId: organization.id, operationType: "GEMINI_SMOKE" } }); console.log(JSON.stringify({ provider: result.provider, model: result.model, success: true, latencyMs: result.latencyMs, usage: result.usage, providerCostMicros: event.providerCostMicros?.toString(), creditUnits: event.creditsChargedUnits.toString() }));
} finally { if (process.env.AI_SMOKE_CLEANUP === "1") { await db.organization.delete({ where: { id: organization.id } }); await db.user.delete({ where: { id: user.id } }); } }
