import type {
  SimulatorScenario,
  SimulatorScenarioDefinition,
} from "../types";

export const scenarios: Record<
  SimulatorScenario,
  SimulatorScenarioDefinition
> = {
  restaurant: {
    id: "restaurant",
    title: "Restaurant Commerce",
    businessName: "Island Flame",
    industry: "Restaurant / Food",
    location: "Montego Bay, Jamaica",
    goal: "Online ordering + reservations",
    currency: "JMD",
    style: "Premium Caribbean Dining",
    primary: "#ff6a2a",
    secondary: "#ffbf69",
    background: "#120b08",
    pages: [
      "Home",
      "Menu",
      "Order Online",
      "Reservations",
      "About",
      "Gallery",
      "Delivery",
      "Contact",
    ],
    features: [
      "Online ordering",
      "Reservations",
      "WhatsApp",
      "Delivery",
      "Menu management",
      "Customer checkout",
    ],
    database: [
      "Products",
      "Categories",
      "Orders",
      "Customers",
      "Reservations",
    ],
    integrations: [
      "WhatsApp",
      "SLYDE Delivery",
      "Online Payments",
    ],
    prompt:
      "Build a premium restaurant website for Island Flame in Montego Bay with menu, online ordering, reservations, WhatsApp and SLYDE delivery.",
  },

  fashion: {
    id: "fashion",
    title: "Fashion Commerce",
    businessName: "Aura876",
    industry: "Fashion / Retail",
    location: "Kingston, Jamaica",
    goal: "Sell fashion online",
    currency: "JMD",
    style: "Luxury Editorial Commerce",
    primary: "#d5b98f",
    secondary: "#f4eee5",
    background: "#0d0d0d",
    pages: [
      "Home",
      "Shop",
      "Collections",
      "New Arrivals",
      "Product",
      "Cart",
      "Account",
      "Contact",
    ],
    features: [
      "Product catalogue",
      "Cart",
      "Checkout",
      "Customer accounts",
      "Inventory",
      "Delivery",
    ],
    database: [
      "Products",
      "Variants",
      "Inventory",
      "Customers",
      "Orders",
    ],
    integrations: [
      "Payments",
      "Delivery",
      "Email",
    ],
    prompt:
      "Create a luxury Jamaican fashion store called Aura876 with products, customer accounts, cart, checkout and delivery.",
  },

  villa: {
    id: "villa",
    title: "Hospitality Booking",
    businessName: "Azure Cove",
    industry: "Villa / Hospitality",
    location: "Negril, Jamaica",
    goal: "Direct property bookings",
    currency: "USD",
    style: "Caribbean Luxury",
    primary: "#118fa5",
    secondary: "#e7d9bd",
    background: "#071b22",
    pages: [
      "Home",
      "Stay",
      "Gallery",
      "Amenities",
      "Availability",
      "Book",
      "Experiences",
      "Contact",
    ],
    features: [
      "Availability",
      "Booking",
      "Guest checkout",
      "Gallery",
      "Amenities",
      "Airport transport",
    ],
    database: [
      "Guests",
      "Bookings",
      "Availability",
      "Payments",
      "Experiences",
    ],
    integrations: [
      "Payments",
      "Transport",
      "Email",
    ],
    prompt:
      "Build a premium villa booking website in Negril with availability, gallery, reservations, payments and airport transportation.",
  },

  business: {
    id: "business",
    title: "Professional Business",
    businessName: "StoneCraft",
    industry: "Construction",
    location: "Jamaica",
    goal: "Generate qualified leads",
    currency: "JMD",
    style: "Modern Architectural",
    primary: "#d5a84b",
    secondary: "#e6e6e6",
    background: "#111315",
    pages: [
      "Home",
      "About",
      "Services",
      "Projects",
      "Process",
      "Testimonials",
      "Quote",
      "Contact",
    ],
    features: [
      "Quote requests",
      "Project gallery",
      "WhatsApp",
      "Lead forms",
      "Testimonials",
    ],
    database: [
      "Leads",
      "Projects",
      "Testimonials",
      "Requests",
    ],
    integrations: [
      "WhatsApp",
      "Email",
      "Maps",
    ],
    prompt:
      "Create a modern website for a construction company with projects, services, quote requests and WhatsApp.",
  },

  saas: {
    id: "saas",
    title: "SaaS Platform",
    businessName: "Ledgerly",
    industry: "Financial Software",
    location: "Global",
    goal: "Acquire SaaS customers",
    currency: "USD",
    style: "Modern SaaS",
    primary: "#7c68ff",
    secondary: "#52d6ff",
    background: "#090b16",
    pages: [
      "Home",
      "Product",
      "Solutions",
      "Pricing",
      "Dashboard",
      "Login",
      "Register",
      "Contact",
    ],
    features: [
      "Authentication",
      "Subscriptions",
      "Dashboard",
      "Pricing",
      "Teams",
      "Billing",
    ],
    database: [
      "Users",
      "Organizations",
      "Subscriptions",
      "Invoices",
      "Activity",
    ],
    integrations: [
      "Payments",
      "Email",
      "Analytics",
    ],
    prompt:
      "Build a modern SaaS website for an accounting platform with pricing, login, dashboard preview and subscriptions.",
  },
};
