import assert from "node:assert/strict";
import { test } from "node:test";
import { z } from "zod";
import type { AiEnvironment } from "@zayloq/config";
import { AiError } from "../errors/ai-error.js";
import { ModelResolver } from "../models/model-resolver.js";
import { AiProviderRegistry } from "../providers/registry.js";
import { TestAiProvider } from "../testing/test-provider.js";
import { AiGateway } from "./ai-gateway.js";
import { InMemoryConcurrencyController } from "./concurrency.js";
const config: AiEnvironment = { OPENAI_API_KEY: "test-secret", AI_DEFAULT_PROVIDER: "OPENAI", AI_FAST_MODEL: "fast-test", AI_REASONING_MODEL: "reasoning-test", AI_GENERATION_MODEL: "generation-test", AI_REQUEST_TIMEOUT_MS: 50, AI_MAX_OUTPUT_TOKENS: 100, AI_MAX_REQUEST_CHARS: 100, AI_RETRY_ATTEMPTS: 2, AI_GLOBAL_CONCURRENCY: 2, AI_ORGANIZATION_CONCURRENCY: 1, AI_USER_CONCURRENCY: 1 };
const request = { task: "text" as const, modelRole: "FAST" as const, messages: [{ role: "user" as const, content: "hello" }] };
function gateway(provider: TestAiProvider, concurrency = new InMemoryConcurrencyController({ global: 2, organization: 1, user: 1 })) { return new AiGateway(config, new AiProviderRegistry().register(provider), concurrency); }
test("provider registration, unknown rejection, and logical model resolution", () => { const provider = new TestAiProvider(); assert.equal(new AiProviderRegistry().register(provider).get("OPENAI"), provider); assert.throws(() => new AiProviderRegistry().get("OPENAI"), (error: unknown) => error instanceof AiError && error.code === "UNKNOWN_PROVIDER"); assert.deepEqual(["FAST", "REASONING", "GENERATION"].map((role) => new ModelResolver(config).resolve(role as "FAST" | "REASONING" | "GENERATION")), ["fast-test", "reasoning-test", "generation-test"]); });
test("normalizes text and usage", async () => { const result = await gateway(new TestAiProvider({ text: "ready", usage: { inputTokens: 2, outputTokens: 1, totalTokens: 3 } })).generateText(request); assert.equal(result.output, "ready"); assert.deepEqual(result.usage, { inputTokens: 2, outputTokens: 1, totalTokens: 3 }); assert.equal(result.model, "fast-test"); });
test("validates structured output and rejects invalid output", async () => { const schema = z.object({ ready: z.boolean() }); assert.deepEqual((await gateway(new TestAiProvider({ structured: { ready: true } })).generateStructured({ ...request, task: "structured", schemaName: "ready", schema })).output, { ready: true }); await assert.rejects(() => gateway(new TestAiProvider({ structured: { ready: "yes" } })).generateStructured({ ...request, task: "structured", schemaName: "ready", schema }), (error: unknown) => error instanceof AiError && error.code === "INVALID_PROVIDER_RESPONSE"); });
test("times out and supports caller cancellation", async () => { await assert.rejects(() => gateway(new TestAiProvider({ behavior: "hang" })).generateText({ ...request, timeoutMs: 5 }), (error: unknown) => error instanceof AiError && error.code === "TIMEOUT"); const controller = new AbortController(); const pending = gateway(new TestAiProvider({ behavior: "hang" })).generateText({ ...request, signal: controller.signal }); controller.abort(); await assert.rejects(() => pending, (error: unknown) => error instanceof AiError && error.code === "CANCELLED"); });
test("retries transient failures but not rejected requests", async () => { const transient = new TestAiProvider({ behavior: "transient" }); const result = await gateway(transient).generateText(request); assert.equal(result.retryCount, 1); assert.equal(transient.calls, 2); const rejected = new TestAiProvider({ behavior: "rejected" }); await assert.rejects(() => gateway(rejected).generateText(request), (error: unknown) => error instanceof AiError && error.code === "PROVIDER_REJECTED"); assert.equal(rejected.calls, 1); });
test("enforces request size and concurrency", async () => { await assert.rejects(() => gateway(new TestAiProvider()).generateText({ ...request, messages: [{ role: "user", content: "x".repeat(101) }] }), (error: unknown) => error instanceof AiError && error.code === "REQUEST_TOO_LARGE"); const control = new InMemoryConcurrencyController({ global: 1, organization: 1, user: 1 }); const lease = await control.acquire({ userId: "u" }); await assert.rejects(() => control.acquire({ userId: "u" }), (error: unknown) => error instanceof AiError && error.code === "CONCURRENCY_LIMITED"); await lease.release(); });
